"""Minimal backtest engine.

Temporal convention (CRITICAL — prevents look-ahead bias):

    information available at t: prices[0], ..., prices[t]
            ↓
    signal[t] = strategy.generate_signal(data)[t]
            ↓
    position[t] = signal[t]   (execution at close of period t)
            ↓
    asset_return[t+1] = prices[t+1] / prices[t] - 1
            ↓
    strategy_return[t+1] = position[t] * asset_return[t+1]

This means:
    - signal[t] is determined by information through period t.
    - position[t] is active during period t+1.
    - strategy_return[t] uses position[t-1] and asset_return[t].

The engine explicitly shifts signals by 1 to enforce this alignment.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from quant_engine.backtest.data import PriceData
    from quant_engine.backtest.strategy import Strategy


@dataclass(frozen=True)
class BacktestOutput:
    """Full output of a backtest run.

    Contains all arrays needed to audit the simulation.
    Every array has the same length: n_periods - 1 (one per return period).

    Attributes:
        strategy_name: Name of the strategy.
        timestamps: Integer timestamps for each return period [1, 2, ..., n-1].
        prices: Prices array (full length, for reference).
        asset_returns: Simple asset returns for each period.
        signals: Signals generated by strategy (full length, shifted for alignment).
        positions: Positions held during each return period (shifted signals).
        strategy_returns: Strategy returns = position * asset_return.
        transaction_costs: Transaction costs per period (currently all zeros).
        total_return: Cumulative strategy return.
        cost_assumption: Documentation of cost model.
    """

    strategy_name: str
    timestamps: np.ndarray
    prices: np.ndarray
    asset_returns: np.ndarray
    signals: np.ndarray
    positions: np.ndarray
    strategy_returns: np.ndarray
    transaction_costs: np.ndarray
    total_return: float
    cost_assumption: str = "zero_cost"


def run_backtest(data: PriceData, strategy: Strategy) -> BacktestOutput:
    """Execute a backtest.

    Args:
        data: Historical price data.
        strategy: Strategy to evaluate.

    Returns:
        BacktestOutput with all arrays for audit.

    Temporal alignment:
        signals[t] uses info through prices[t].
        positions[t] = signals[t] (active during return period t+1).
        strategy_returns[t] = positions[t] * asset_returns[t].

        where asset_returns[t] = prices[t+1]/prices[t] - 1.

        So strategy_returns[0] = positions[0] * asset_returns[0]
                               = signals[0] * (prices[1]/prices[0] - 1)

        And strategy_returns[t] corresponds to the return earned
        from holding position[t] through period t+1.
    """
    prices = data.prices
    n = len(prices)

    # Generate signals: signal[t] uses information through prices[t]
    signals = strategy.generate_signal(data)

    # Validate signal length
    if len(signals) != n:
        raise ValueError(
            f"Signal length ({len(signals)}) must match price length ({n})"
        )

    # Validate signal values
    unique_vals = set(np.unique(signals))
    valid_vals = {-1.0, 0.0, 1.0}
    if not unique_vals.issubset(valid_vals):
        raise ValueError(
            f"Signals must be in {{-1, 0, 1}}, got unique values: {unique_vals}"
        )

    # Asset returns: asset_returns[t] = prices[t+1]/prices[t] - 1
    asset_returns = np.diff(prices) / prices[:-1]

    # Temporal alignment: position[t] = signal[t], active for return[t+1]
    # So positions for returns are signals[0:n-1]
    positions = signals[:-1]

    # Strategy returns: strategy_returns[t] = positions[t] * asset_returns[t]
    strategy_returns = positions * asset_returns

    # Transaction costs: zero for now
    transaction_costs = np.zeros(n - 1)

    # Net returns (currently identical to strategy returns)
    net_returns = strategy_returns - transaction_costs

    # Total cumulative return
    total_return = float(np.prod(1.0 + net_returns) - 1.0)

    # Timestamps for return periods
    timestamps = np.arange(1, n)

    return BacktestOutput(
        strategy_name=strategy.name,
        timestamps=timestamps,
        prices=prices,
        asset_returns=asset_returns,
        signals=signals,
        positions=positions,
        strategy_returns=net_returns,
        transaction_costs=transaction_costs,
        total_return=total_return,
    )
