"""Canonical market data models.

Provider-independent representation of market data records.
All timestamps are UTC, timezone-aware. All records have deterministic IDs.

Timestamp policy:
    - source_timestamp: when the market event was generated by the provider
    - ingestion_timestamp: when our system received/recorded it
    - Both must be UTC, timezone-aware
    - Never accept naive datetimes
    - source_timestamp_missing: True when the provider does not expose a
      source timestamp (e.g., Kalshi orderbook). In this case,
      source_timestamp is set to ingestion_timestamp for storage purposes,
      but source_timestamp_missing documents that it is NOT the actual
      exchange-side event time. This distinction matters for:
      - look-ahead bias prevention
      - latency research
      - event alignment
      - replay ordering

Price/size semantics:
    - float representation for NumPy/Polars/Arrow compatibility
    - Domain constraints enforced by validation, not the model
    - None represents absent side (not 0, not NaN)

Record identity:
    - SHA-256 of canonical JSON of (provider, provider_instrument_id,
      source_timestamp, bid_price, bid_size, ask_price, ask_size)
    - Truncated to 16 hex chars
    - Same payload always produces same ID
    - When source_timestamp_missing=True, source_timestamp is excluded from
      the hash to ensure the same logical data always has the same record_id
      regardless of when it was ingested.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field, model_validator

from quant_engine.market_data.errors import InvalidTimestampError


def _utc_now() -> datetime:
    """Current UTC time, timezone-aware."""
    return datetime.now(UTC)


class MarketQuote(BaseModel):
    """Canonical market quote record.

    Represents a single point-in-time quote for an instrument from a provider.
    The record is provider-independent after normalization.

    Attributes:
        source_timestamp: When the provider generated this quote (UTC).
        source_timestamp_missing: True when the provider does not expose a
            source timestamp. When True, source_timestamp is set to
            ingestion_timestamp and should NOT be treated as the actual
            exchange-side event time.
        ingestion_timestamp: When our system received this quote (UTC).
        provider: Provider identifier (e.g. "polymarket", "kalshi").
        provider_instrument_id: Provider's instrument identifier.
        bid_price: Best bid price (None if no bid available).
        bid_size: Best bid size (None if no bid available).
        ask_price: Best ask price (None if no bid available).
        ask_size: Best ask size (None if no bid available).
        schema_version: Schema version for forward compatibility.
    """

    model_config = {"frozen": True}

    # Timestamps — both must be UTC, timezone-aware
    source_timestamp: datetime
    source_timestamp_missing: bool = False
    ingestion_timestamp: datetime

    # Instrument identity
    provider: str = Field(min_length=1)
    provider_instrument_id: str = Field(min_length=1)

    # Quote data — None means side not available
    bid_price: float | None = None
    bid_size: float | None = None
    ask_price: float | None = None
    ask_size: float | None = None

    # Metadata
    schema_version: str = "1"

    @model_validator(mode="after")
    def _validate_timestamps(self) -> MarketQuote:
        """Reject naive timestamps."""
        if self.source_timestamp.tzinfo is None:
            raise InvalidTimestampError(
                "source_timestamp must be timezone-aware (UTC), got naive datetime"
            )
        if self.ingestion_timestamp.tzinfo is None:
            raise InvalidTimestampError(
                "ingestion_timestamp must be timezone-aware (UTC), got naive datetime"
            )
        return self

    @property
    def record_id(self) -> str:
        """Deterministic record identifier.

        Derived from canonical JSON of core fields.
        Same payload always produces the same record_id.
        """
        canonical = self._canonical_payload()
        return hashlib.sha256(canonical.encode()).hexdigest()[:16]

    def _canonical_payload(self) -> str:
        """Canonical JSON for record ID derivation.

        When source_timestamp_missing=True, source_timestamp is excluded from
        the hash. This ensures the same logical data always has the same
        record_id regardless of when it was ingested.
        """
        d: dict[str, object] = {
            "provider": self.provider,
            "provider_instrument_id": self.provider_instrument_id,
            "bid_price": self.bid_price,
            "bid_size": self.bid_size,
            "ask_price": self.ask_price,
            "ask_size": self.ask_size,
        }
        if not self.source_timestamp_missing:
            d["source_timestamp"] = self.source_timestamp.isoformat()
        return json.dumps(d, sort_keys=True, separators=(",", ":"), ensure_ascii=True)

    def to_dict(self) -> dict[str, object]:
        """Serialize to a JSON-compatible dictionary."""
        return {
            "source_timestamp": self.source_timestamp.isoformat(),
            "source_timestamp_missing": self.source_timestamp_missing,
            "ingestion_timestamp": self.ingestion_timestamp.isoformat(),
            "provider": self.provider,
            "provider_instrument_id": self.provider_instrument_id,
            "bid_price": self.bid_price,
            "bid_size": self.bid_size,
            "ask_price": self.ask_price,
            "ask_size": self.ask_size,
            "schema_version": self.schema_version,
            "record_id": self.record_id,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> MarketQuote:
        """Deserialize from a dictionary."""
        return cls(
            source_timestamp=datetime.fromisoformat(d["source_timestamp"]),
            source_timestamp_missing=bool(d.get("source_timestamp_missing", False)),
            ingestion_timestamp=datetime.fromisoformat(d["ingestion_timestamp"]),
            provider=d["provider"],
            provider_instrument_id=d["provider_instrument_id"],
            bid_price=d.get("bid_price"),
            bid_size=d.get("bid_size"),
            ask_price=d.get("ask_price"),
            ask_size=d.get("ask_size"),
            schema_version=str(d.get("schema_version", "1")),
        )


class Dataset(BaseModel):
    """Ordered collection of canonical market quotes.

    Dataset identity is derived from schema_version and ordered record IDs.
    The same records in the same order always produce the same dataset_id.
    Reordering or changing records changes the dataset_id.

    Attributes:
        schema_version: Schema version for the dataset.
        records: Ordered list of MarketQuote records.
    """

    model_config = {"frozen": True}

    schema_version: str = "1"
    records: list[MarketQuote]

    @property
    def dataset_id(self) -> str:
        """Deterministic dataset identifier.

        Derived from schema_version and sorted record IDs.
        Records are sorted by (sort_timestamp, record_id) to ensure
        the same logical dataset always produces the same ID regardless
        of insertion order.

        When source_timestamp_missing=True, uses ingestion_timestamp
        for sorting (since source_timestamp is not meaningful).
        """
        records_with_id = [(r, r.record_id) for r in self.records]

        def _sort_key(item: tuple[MarketQuote, str]) -> tuple[str, str]:
            r, rid = item
            if r.source_timestamp_missing:
                ts = r.ingestion_timestamp.isoformat()
            else:
                ts = r.source_timestamp.isoformat()
            return (ts, rid)

        records_with_id.sort(key=_sort_key)
        record_ids = [rid for _, rid in records_with_id]
        canonical = json.dumps(
            {
                "schema_version": self.schema_version,
                "record_ids": record_ids,
            },
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
        )
        return hashlib.sha256(canonical.encode()).hexdigest()[:16]

    def to_dict(self) -> dict[str, object]:
        """Serialize to a JSON-compatible dictionary."""
        return {
            "schema_version": self.schema_version,
            "records": [r.to_dict() for r in self.records],
            "dataset_id": self.dataset_id,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Dataset:
        """Deserialize from a dictionary."""
        return cls(
            schema_version=str(d.get("schema_version", "1")),
            records=[MarketQuote(**r) for r in d["records"]],
        )
